version: '3.4'

services:
  contentservice:
    image: contentservice
    depends_on:
        - databaseservice
        - eventbus
    build:
      context: .
      dockerfile: ContentService/Dockerfile
    ports:
    - "6007:80"
    - "6008:443"
  authservice:
    image: authservice
    depends_on:
        - databaseservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
    - "6009:80"
    - "6010:443"
  apigateway:
    image: apigatewayservice
    depends_on:
        - eventbus
        - contentservice
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
    - "6001:80"
    - "6002:443"
  announcementservice:
    image: announcementservice
    depends_on:
        - eventbus
    build:
      context: .
      dockerfile: AnnouncementService/Dockerfile
    ports:
      - "6003:80"
      - "6004:443"
  databaseservice:
    image: databasemanagementservice
    depends_on:
        - db
    build:
      context: .
      dockerfile: DatabaseManagementService/Dockerfile
    ports:
    - "6005:80"
    - "6006:443"
  db:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: D@s_!$T_Me1n_KennW0rt!
        MONGO_INITDB_DATABASE: WeltWerkDb
    ports:
    - "27017:27017"
  eventbus:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"